// Data here is the files from static/exampleTableData but as base64 encoding so can be written to drive
export default {
	Readme: `### Collections\n\nNew collections of tables should sit under\n'Fantasy-Tables/Collections'\nwithin their own folder, inside each uniquely named folder should be an index.json file eg:\n'Fantasy-Tables/Collections/castles/index.json'\n\n### Views\n\nNew views should be placed under\n'Fantasy-Tables/Views'`,
	castlesIndex: `{"collectionID": "castle","collectionName": "Medieval Castles","category": "Place","isUtility": false,"tags": ["place", "medieval", "low-fantasy"],"tables": { "castle": ["medieval"], "castle-japan": ["japanese"] }}`,
	castlesMain: `{"medieval": {"label": "Medieval European Castle","tableSections": [{"id": "castle-name","name": "Castle Name","table": ["{{names/place/medieval:Name}} Castle", "{{names/place/medieval:Name}} Redoubt"],"type": "simple"},{"id": "castle-type","name": "Castle Type:","table": ["large wooden Castle", "Small hillfort"],"type": "simple"}]},"test": {"label": "Test multiname packet","tableSections": [{"id": "castle-name","name": "Castle Name","table": ["{{names/place/medieval:Name}}-{{names/place/japan:Name}} Castle"],"type": "simple"}]},"testDefault": {"label": "Test No collection & backup call value","tableSections": [{"id": "castle-name","name": "Castle Name","table": ["{{names/place/SDFD:Name}} Castle"],"type": "simple"}]}}`,
	castlesJapan: `{"japanese": {"label": "Japanese Castle","tableSections": [{"id": "castle-name","name": "Castle Name:","table": ["{{names/place/japan:Name}} Castle", "{{names/place/japan:Name}} Fort"],"type": "simple"},{"id": "castle-type","name": "Castle Type:","table": ["large wooden Castle", "Small hillfort"],"type": "simple"}]}}`,
	namesIndex: `{"collectionID":"names","collectionName":"Names","category":"Utility","isUtility":true,"tags":["names","medieval","low-fantasy"],"tables":{"place":["medieval","japan","nest"]}}`,
	placesFolder: '/place.json',
	namesPlaces: `{"medieval":{"id":"castle-name","name":"CastleName:","table":["Wigville","Tyrist","Yeville"]},"japan":{"id":"castle-name","name":"CastleName:","table":["Himejo","Yurijo","Kannoji"]},"nest":{"id":"nest-name","name":"CastleName:","table":["{{names/place/japan:A}}--{{names/place/medieval:B}}","{{names/place/medieval:A}}--{{names/place/medieval:B}}"]}}`
};
